---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: location-soa-rest
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: org.mycompany
  name: location-soa-rest
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: location-soa-rest
    provider: jkube
    group: org.mycompany
